version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: monorepo-gym-mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./docker/init-database.sql:/tmp/init-database.sql
    command: >
      bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 30s &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${MSSQL_SA_PASSWORD}' -d master -i /tmp/init-database.sql -C &&
      wait
      "

volumes:
  mssql_data:
    driver: local
