const JWT_EXPIRES_IN_15_MINUTES_IN_SECONDS = 60 * 15
const JWT_EXPIRES_IN_7_DAYS_IN_SECONDS = 60 * 60 * 24 * 7
const JWT_EXPIRES_IN_7_DAYS_IN_MILISECONDS = JWT_EXPIRES_IN_7_DAYS_IN_SECONDS * 1000

export {
  JWT_EXPIRES_IN_15_MINUTES_IN_SECONDS,
  JWT_EXPIRES_IN_7_DAYS_IN_SECONDS,
  JWT_EXPIRES_IN_7_DAYS_IN_MILISECONDS
}