const JWT_EXPIRES_IN_15_MINUTES_IN_SECONDS = 60 * 15
const JWT_EXPIRES_IN_7_DAYS_IN_SECONDS = 60 * 60 * 24 * 7
const JWT_EXPIRES_IN_7_DAYS_IN_MILISECONDS = JWT_EXPIRES_IN_7_DAYS_IN_SECONDS * 1000

enum USER_ROLE {
  ADMIN = 'ADMIN',
  STUDENT = 'STUDENT',
  PROFESSOR = 'PROFESSOR'
}

enum IMC_CLASSFICATION {
  UNDERWEIGHT = 'UNDERWEIGHT',
  NORMAL = 'NORMAL',
  OVERWEIGHT = 'OVERWEIGHT',
  OBESE_I = 'OBESE_I',
  OBESE_II = 'OBESE_II',
  OBESE_III = 'OBESE_III',
}

export {
  JWT_EXPIRES_IN_15_MINUTES_IN_SECONDS,
  JWT_EXPIRES_IN_7_DAYS_IN_SECONDS,
  JWT_EXPIRES_IN_7_DAYS_IN_MILISECONDS,
  USER_ROLE,
  IMC_CLASSFICATION
}