const JWT_EXPIRES_IN_15_MINUTES_IN_SECONDS = 60 * 15
const JWT_EXPIRES_IN_7_DAYS_IN_SECONDS = 60 * 60 * 24 * 7
const JWT_EXPIRES_IN_7_DAYS_IN_MILISECONDS = JWT_EXPIRES_IN_7_DAYS_IN_SECONDS * 1000

enum USER_ROLE {
  ADMIN = 'ADMIN',
  STUDENT = 'STUDENT',
  PROFESSOR = 'PROFESSOR'
}

enum IMC_CLASSFICATION {
  UNDERWEIGHT = 'UNDERWEIGHT',
  NORMAL = 'NORMAL',
  OVERWEIGHT = 'OVERWEIGHT',
  OBESE_I = 'OBESE_I',
  OBESE_II = 'OBESE_II',
  OBESE_III = 'OBESE_III',
}

const IMC_CLASSIFICATION_TO_LABEL: Record<IMC_CLASSFICATION, string> = {
  [IMC_CLASSFICATION.UNDERWEIGHT]: 'Abaixo do peso',
  [IMC_CLASSFICATION.NORMAL]: 'Peso normal',
  [IMC_CLASSFICATION.OVERWEIGHT]: 'Sobrepreso',
  [IMC_CLASSFICATION.OBESE_I]: 'Obesidade grau I',
  [IMC_CLASSFICATION.OBESE_II]: 'Obesidade grau II',
  [IMC_CLASSFICATION.OBESE_III]: 'Obesidade grau III',
}

export {
  JWT_EXPIRES_IN_15_MINUTES_IN_SECONDS,
  JWT_EXPIRES_IN_7_DAYS_IN_SECONDS,
  JWT_EXPIRES_IN_7_DAYS_IN_MILISECONDS,
  USER_ROLE,
  IMC_CLASSFICATION,
  IMC_CLASSIFICATION_TO_LABEL
}